import { Ingredient, Recipe, FriendPost, UserProfile } from "./types";

export const mockIngredients: Ingredient[] = [
  {
    id: "1",
    name: "Baby Spinach",
    quantity: "5",
    unit: "oz",
    expiryDate: "2026-05-10",
    daysLeft: 1,
    urgency: "red",
    estimatedValue: 3.5,
    emoji: "🥬",
    isShared: true,
    autoShared: true,
  },
  {
    id: "2",
    name: "Strawberries",
    quantity: "1",
    unit: "pint",
    expiryDate: "2026-05-11",
    daysLeft: 2,
    urgency: "red",
    estimatedValue: 5.0,
    emoji: "🍓",
    isShared: true,
    autoShared: true,
  },
  {
    id: "3",
    name: "Roma Tomatoes",
    quantity: "4",
    unit: "count",
    expiryDate: "2026-05-13",
    daysLeft: 4,
    urgency: "yellow",
    estimatedValue: 2.5,
    emoji: "🍅",
    isShared: false,
    autoShared: false,
  },
  {
    id: "4",
    name: "Carrots",
    quantity: "1",
    unit: "bag",
    expiryDate: "2026-05-13",
    daysLeft: 4,
    urgency: "yellow",
    estimatedValue: 2.0,
    emoji: "🥕",
    isShared: false,
    autoShared: false,
  },
  {
    id: "5",
    name: "Cheddar Cheese",
    quantity: "8",
    unit: "oz",
    expiryDate: "2026-05-21",
    daysLeft: 12,
    urgency: "green",
    estimatedValue: 4.0,
    emoji: "🧀",
    isShared: false,
    autoShared: false,
  },
  {
    id: "6",
    name: "Eggs",
    quantity: "8",
    unit: "count",
    expiryDate: "2026-05-23",
    daysLeft: 14,
    urgency: "green",
    estimatedValue: 3.0,
    emoji: "🥚",
    isShared: false,
    autoShared: false,
  },
  {
    id: "7",
    name: "All-Purpose Flour",
    quantity: "3",
    unit: "lbs",
    expiryDate: "2026-11-01",
    daysLeft: 176,
    urgency: "green",
    estimatedValue: 4.5,
    emoji: "🌾",
    isShared: true,
    autoShared: false,
  },
  {
    id: "8",
    name: "Whole Milk",
    quantity: "1",
    unit: "gallon",
    expiryDate: "2026-05-16",
    daysLeft: 7,
    urgency: "green",
    estimatedValue: 5.0,
    emoji: "🥛",
    isShared: false,
    autoShared: false,
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    name: "Spinach Strawberry Salad",
    emoji: "🥗",
    cookTime: "10 min",
    difficulty: "Easy",
    expiringIngredients: ["Baby Spinach", "Strawberries"],
    allIngredients: ["Baby Spinach", "Strawberries", "Cheddar Cheese", "Lemon"],
    savingsEstimate: 8,
  },
  {
    id: "2",
    name: "Spinach & Egg Scramble",
    emoji: "🍳",
    cookTime: "15 min",
    difficulty: "Easy",
    expiringIngredients: ["Baby Spinach", "Eggs"],
    allIngredients: ["Baby Spinach", "Eggs", "Cheddar Cheese"],
    savingsEstimate: 5,
  },
  {
    id: "3",
    name: "Tomato Carrot Soup",
    emoji: "🍲",
    cookTime: "30 min",
    difficulty: "Medium",
    expiringIngredients: ["Roma Tomatoes", "Carrots"],
    allIngredients: ["Roma Tomatoes", "Carrots", "Whole Milk"],
    savingsEstimate: 4,
  },
  {
    id: "4",
    name: "Strawberry Smoothie",
    emoji: "🥤",
    cookTime: "5 min",
    difficulty: "Easy",
    expiringIngredients: ["Strawberries"],
    allIngredients: ["Strawberries", "Whole Milk"],
    savingsEstimate: 5,
  },
];

export const mockFriendPosts: FriendPost[] = [
  {
    id: "1",
    friendName: "Jessica Lee",
    friendInitials: "JL",
    ingredientName: "Spinach",
    ingredientEmoji: "🥬",
    daysLeft: 1,
    urgency: "red",
    quantity: "Half a bag",
    isAutoShared: true,
    requested: false,
  },
  {
    id: "2",
    friendName: "Marcus R.",
    friendInitials: "MR",
    ingredientName: "Lemons",
    ingredientEmoji: "🍋",
    daysLeft: 5,
    urgency: "green",
    quantity: "4 count",
    isAutoShared: false,
    requested: false,
  },
  {
    id: "3",
    friendName: "Priya S.",
    friendInitials: "PS",
    ingredientName: "Blueberries",
    ingredientEmoji: "🫐",
    daysLeft: 2,
    urgency: "red",
    quantity: "1 pint",
    isAutoShared: true,
    requested: false,
  },
  {
    id: "4",
    friendName: "Marcus R.",
    friendInitials: "MR",
    ingredientName: "Bread Flour",
    ingredientEmoji: "🌾",
    daysLeft: 120,
    urgency: "green",
    quantity: "2 lbs extra",
    isAutoShared: false,
    requested: false,
  },
];

export const mockProfile: UserProfile = {
  name: "Sarah Chen",
  initials: "SC",
  savedThisMonth: 42,
  ingredientsRescued: 17,
  co2Saved: 3.2,
  mealsCooked: 9,
  notifications: [
    {
      id: "1",
      message: "Baby Spinach expires tomorrow — 3 recipes use it",
      time: "2 hours ago",
      type: "warning",
      read: false,
    },
    {
      id: "2",
      message: "Jessica claimed your Strawberries post",
      time: "5 hours ago",
      type: "success",
      read: false,
    },
    {
      id: "3",
      message: "Strawberries expire in 2 days — cook tonight?",
      time: "Yesterday",
      type: "warning",
      read: true,
    },
    {
      id: "4",
      message: "You saved $12 this week by using expiring items!",
      time: "2 days ago",
      type: "success",
      read: true,
    },
  ],
};
