import {
  Ingredient,
  Recipe,
  FriendPost,
  UserProfile,
  IngredientExchangeRequest,
} from "./types";

export const mockIngredients: Ingredient[] = [
  {
    id: "1",
    name: "Baby Spinach",
    quantity: "5",
    unit: "oz",
    count: 1,
    expiryDate: "2026-05-10",
    daysLeft: 1,
    urgency: "red",
    estimatedValue: 3.5,
    emoji: "🥬",
    isShared: true,
    autoShared: true,
  },
  {
    id: "2",
    name: "Strawberries",
    quantity: "1",
    unit: "pint",
    count: 1,
    expiryDate: "2026-05-11",
    daysLeft: 2,
    urgency: "red",
    estimatedValue: 5.0,
    emoji: "🍓",
    isShared: true,
    autoShared: true,
  },
  {
    id: "3",
    name: "Roma Tomatoes",
    quantity: "4",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-13",
    daysLeft: 4,
    urgency: "yellow",
    estimatedValue: 2.5,
    emoji: "🍅",
    isShared: false,
    autoShared: false,
  },
  {
    id: "4",
    name: "Carrots",
    quantity: "1",
    unit: "bag",
    count: 1,
    expiryDate: "2026-05-13",
    daysLeft: 4,
    urgency: "yellow",
    estimatedValue: 2.0,
    emoji: "🥕",
    isShared: false,
    autoShared: false,
  },
  {
    id: "5",
    name: "Cheddar Cheese",
    quantity: "8",
    unit: "oz",
    count: 1,
    expiryDate: "2026-05-21",
    daysLeft: 12,
    urgency: "green",
    estimatedValue: 4.0,
    emoji: "🧀",
    isShared: false,
    autoShared: false,
  },
  {
    id: "6",
    name: "Eggs",
    quantity: "8",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-23",
    daysLeft: 14,
    urgency: "green",
    estimatedValue: 3.0,
    emoji: "🥚",
    isShared: false,
    autoShared: false,
  },
  {
    id: "7",
    name: "All-Purpose Flour",
    quantity: "3",
    unit: "lbs",
    count: 1,
    expiryDate: "2026-11-01",
    daysLeft: 176,
    urgency: "green",
    estimatedValue: 4.5,
    emoji: "🌾",
    isShared: true,
    autoShared: false,
  },
  {
    id: "8",
    name: "Whole Milk",
    quantity: "1",
    unit: "gallon",
    count: 1,
    expiryDate: "2026-05-16",
    daysLeft: 7,
    urgency: "green",
    estimatedValue: 5.0,
    emoji: "🥛",
    isShared: false,
    autoShared: false,
  },
  {
    id: "9",
    name: "Onions",
    quantity: "3",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-18",
    daysLeft: 9,
    urgency: "green",
    estimatedValue: 2.4,
    emoji: "🧅",
    isShared: false,
    autoShared: false,
  },
  {
    id: "10",
    name: "Garlic",
    quantity: "1",
    unit: "bunch",
    count: 1,
    expiryDate: "2026-05-25",
    daysLeft: 16,
    urgency: "green",
    estimatedValue: 1.5,
    emoji: "🧄",
    isShared: false,
    autoShared: false,
  },
  {
    id: "11",
    name: "Bell Peppers",
    quantity: "3",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-15",
    daysLeft: 6,
    urgency: "yellow",
    estimatedValue: 3.25,
    emoji: "🫑",
    isShared: false,
    autoShared: false,
  },
  {
    id: "12",
    name: "Broccoli",
    quantity: "2",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-14",
    daysLeft: 5,
    urgency: "yellow",
    estimatedValue: 2.75,
    emoji: "🥦",
    isShared: false,
    autoShared: false,
  },
  {
    id: "13",
    name: "Bananas",
    quantity: "6",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-12",
    daysLeft: 3,
    urgency: "yellow",
    estimatedValue: 2.9,
    emoji: "🍌",
    isShared: false,
    autoShared: false,
  },
  {
    id: "14",
    name: "Apples",
    quantity: "5",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-21",
    daysLeft: 12,
    urgency: "green",
    estimatedValue: 4.5,
    emoji: "🍎",
    isShared: false,
    autoShared: false,
  },
  {
    id: "15",
    name: "Chicken Breast",
    quantity: "2",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-11",
    daysLeft: 2,
    urgency: "red",
    estimatedValue: 9.0,
    emoji: "🍗",
    isShared: true,
    autoShared: true,
  },
  {
    id: "16",
    name: "Rice",
    quantity: "2",
    unit: "lbs",
    count: 1,
    expiryDate: "2026-11-30",
    daysLeft: 205,
    urgency: "green",
    estimatedValue: 3.4,
    emoji: "🍚",
    isShared: false,
    autoShared: false,
  },
  {
    id: "17",
    name: "Pasta",
    quantity: "2",
    unit: "lbs",
    count: 1,
    expiryDate: "2026-12-15",
    daysLeft: 220,
    urgency: "green",
    estimatedValue: 3.8,
    emoji: "🍝",
    isShared: false,
    autoShared: false,
  },
  {
    id: "18",
    name: "Potatoes",
    quantity: "5",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-24",
    daysLeft: 15,
    urgency: "green",
    estimatedValue: 3.2,
    emoji: "🥔",
    isShared: false,
    autoShared: false,
  },
  {
    id: "19",
    name: "Lemons",
    quantity: "4",
    unit: "count",
    count: 1,
    expiryDate: "2026-05-16",
    daysLeft: 7,
    urgency: "yellow",
    estimatedValue: 2.2,
    emoji: "🍋",
    isShared: false,
    autoShared: false,
  },
  {
    id: "20",
    name: "Butter",
    quantity: "8",
    unit: "oz",
    count: 1,
    expiryDate: "2026-06-10",
    daysLeft: 32,
    urgency: "green",
    estimatedValue: 4.6,
    emoji: "🧈",
    isShared: false,
    autoShared: false,
  },
  {
    id: "21",
    name: "Mushrooms",
    quantity: "1",
    unit: "bag",
    count: 1,
    expiryDate: "2026-05-12",
    daysLeft: 3,
    urgency: "yellow",
    estimatedValue: 2.9,
    emoji: "🍄",
    isShared: false,
    autoShared: false,
  },
  {
    id: "22",
    name: "Yogurt",
    quantity: "1",
    unit: "pint",
    count: 1,
    expiryDate: "2026-05-17",
    daysLeft: 8,
    urgency: "yellow",
    estimatedValue: 3.1,
    emoji: "🫙",
    isShared: false,
    autoShared: false,
  },
  {
    id: "23",
    name: "Olive Oil",
    quantity: "1",
    unit: "bottle",
    count: 1,
    expiryDate: "2026-12-20",
    daysLeft: 225,
    urgency: "green",
    estimatedValue: 8.5,
    emoji: "🫒",
    isShared: false,
    autoShared: false,
  },
  {
    id: "24",
    name: "Parmesan",
    quantity: "6",
    unit: "oz",
    count: 1,
    expiryDate: "2026-06-08",
    daysLeft: 30,
    urgency: "green",
    estimatedValue: 5.2,
    emoji: "🧀",
    isShared: false,
    autoShared: false,
  },
  {
    id: "25",
    name: "Basil",
    quantity: "1",
    unit: "bunch",
    count: 1,
    expiryDate: "2026-05-12",
    daysLeft: 3,
    urgency: "yellow",
    estimatedValue: 2.0,
    emoji: "🌿",
    isShared: false,
    autoShared: false,
  },
  {
    id: "26",
    name: "Tomato Sauce",
    quantity: "2",
    unit: "cup",
    count: 1,
    expiryDate: "2026-07-20",
    daysLeft: 72,
    urgency: "green",
    estimatedValue: 3.6,
    emoji: "🍅",
    isShared: false,
    autoShared: false,
  },
  {
    id: "27",
    name: "Ground Beef",
    quantity: "1",
    unit: "lbs",
    count: 1,
    expiryDate: "2026-05-11",
    daysLeft: 2,
    urgency: "red",
    estimatedValue: 7.9,
    emoji: "🥩",
    isShared: true,
    autoShared: true,
  },
  {
    id: "28",
    name: "Black Beans",
    quantity: "2",
    unit: "count",
    count: 1,
    expiryDate: "2027-01-30",
    daysLeft: 266,
    urgency: "green",
    estimatedValue: 2.5,
    emoji: "🫘",
    isShared: false,
    autoShared: false,
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    name: "Spinach Strawberry Salad",
    emoji: "🥗",
    cookTime: "10 min",
    cookTimeMinutes: 10,
    difficulty: "Easy",
    expiringIngredients: ["Baby Spinach", "Strawberries"],
    allIngredients: ["Baby Spinach", "Strawberries", "Cheddar Cheese", "Lemon"],
    savingsEstimate: 8,
    dietaryTags: ["Vegetarian", "Gluten Free"],
    cuisine: "American",
    ingredientMatch: "missing_1",
    steps: [
      "Wash and dry spinach; hull and halve strawberries.",
      "Whisk lemon juice with olive oil, salt, and pepper for the dressing.",
      "Toss spinach and strawberries with dressing; shave cheddar on top.",
      "Serve immediately.",
    ],
  },
  {
    id: "2",
    name: "Spinach & Egg Scramble",
    emoji: "🍳",
    cookTime: "15 min",
    cookTimeMinutes: 15,
    difficulty: "Easy",
    expiringIngredients: ["Baby Spinach", "Eggs"],
    allIngredients: ["Baby Spinach", "Eggs", "Cheddar Cheese"],
    savingsEstimate: 5,
    dietaryTags: ["Vegetarian", "High Protein", "Gluten Free"],
    cuisine: "American",
    ingredientMatch: "pantry_only",
    steps: [
      "Beat eggs with a pinch of salt.",
      "Wilt spinach in a nonstick pan over medium heat.",
      "Pour in eggs; gently fold until softly set.",
      "Fold in grated cheddar and serve hot.",
    ],
  },
  {
    id: "3",
    name: "Tomato Carrot Soup",
    emoji: "🍲",
    cookTime: "30 min",
    cookTimeMinutes: 30,
    difficulty: "Medium",
    expiringIngredients: ["Roma Tomatoes", "Carrots"],
    allIngredients: ["Roma Tomatoes", "Carrots", "Whole Milk"],
    savingsEstimate: 4,
    dietaryTags: ["Vegetarian"],
    cuisine: "Mediterranean",
    ingredientMatch: "missing_2",
    steps: [
      "Rough-chop tomatoes and carrots.",
      "Sweat vegetables until softened; season with salt.",
      "Cover with water or broth; simmer 20 minutes until tender.",
      "Blend until smooth; stir in milk and warm through.",
    ],
  },
  {
    id: "4",
    name: "Strawberry Smoothie",
    emoji: "🥤",
    cookTime: "5 min",
    cookTimeMinutes: 5,
    difficulty: "Easy",
    expiringIngredients: ["Strawberries"],
    allIngredients: ["Strawberries", "Whole Milk"],
    savingsEstimate: 5,
    dietaryTags: ["Vegetarian", "Gluten Free"],
    cuisine: "American",
    ingredientMatch: "pantry_only",
    steps: [
      "Hull strawberries and add to a blender.",
      "Pour in milk and a few ice cubes if you like it cold.",
      "Blend until smooth; taste and adjust sweetness.",
      "Pour into a glass and drink right away.",
    ],
  },
  {
    id: "5",
    name: "Lemon Garlic Pasta",
    emoji: "🍝",
    cookTime: "22 min",
    cookTimeMinutes: 22,
    difficulty: "Easy",
    expiringIngredients: ["Baby Spinach"],
    allIngredients: ["Baby Spinach", "Basil", "Parmesan", "Pasta", "Lemon", "Garlic"],
    savingsEstimate: 9,
    wasteSavings: 9,
    dietaryTags: ["Vegetarian"],
    cuisine: "Italian",
    ingredientMatch: "missing_3",
    usesSources: [
      { ingredientLabel: "spinach", source: "yours" },
      { ingredientLabel: "basil", source: "friend", friendName: "Emma" },
      { ingredientLabel: "parmesan", source: "friend", friendName: "Jason" },
    ],
    steps: [
      "Boil pasta in salted water until al dente; reserve a cup of pasta water.",
      "Sauté sliced garlic in olive oil until fragrant; add lemon zest and juice.",
      "Toss in spinach until wilted; add pasta and a splash of pasta water.",
      "Finish with torn basil and shaved parmesan before serving.",
    ],
  },
];

export const mockExchangeRequests: IngredientExchangeRequest[] = [
  {
    id: "r1",
    direction: "outgoing",
    counterpartyName: "Jessica Lee",
    counterpartyInitials: "JL",
    ingredientName: "Basil",
    ingredientEmoji: "🌿",
    quantity: "1 bunch",
    status: "pending",
  },
  {
    id: "r2",
    direction: "outgoing",
    counterpartyName: "Marcus R.",
    counterpartyInitials: "MR",
    ingredientName: "Lemons",
    ingredientEmoji: "🍋",
    quantity: "4 count",
    status: "approved",
  },
  {
    id: "r3",
    direction: "incoming",
    counterpartyName: "Priya S.",
    counterpartyInitials: "PS",
    ingredientName: "Baby Spinach",
    ingredientEmoji: "🥬",
    quantity: "Half bag",
    status: "pending",
  },
  {
    id: "r4",
    direction: "incoming",
    counterpartyName: "Emma Wilson",
    counterpartyInitials: "EW",
    ingredientName: "Greek Yogurt",
    ingredientEmoji: "🥛",
    quantity: "2 cups",
    status: "pending",
  },
];

export const mockFriendPosts: FriendPost[] = [
  {
    id: "1",
    friendName: "Jessica Lee",
    friendInitials: "JL",
    ingredientName: "Spinach",
    ingredientEmoji: "🥬",
    daysLeft: 1,
    urgency: "red",
    quantity: "Half a bag",
    isAutoShared: true,
    requested: false,
  },
  {
    id: "2",
    friendName: "Marcus R.",
    friendInitials: "MR",
    ingredientName: "Lemons",
    ingredientEmoji: "🍋",
    daysLeft: 5,
    urgency: "green",
    quantity: "4 count",
    isAutoShared: false,
    requested: false,
  },
  {
    id: "3",
    friendName: "Priya S.",
    friendInitials: "PS",
    ingredientName: "Blueberries",
    ingredientEmoji: "🫐",
    daysLeft: 2,
    urgency: "red",
    quantity: "1 pint",
    isAutoShared: true,
    requested: false,
  },
  {
    id: "5",
    friendName: "Noah P.",
    friendInitials: "NP",
    ingredientName: "Celery",
    ingredientEmoji: "🥬",
    daysLeft: 1,
    urgency: "red",
    quantity: "1 bunch",
    isAutoShared: true,
    requested: false,
  },
  {
    id: "4",
    friendName: "Marcus R.",
    friendInitials: "MR",
    ingredientName: "Bread Flour",
    ingredientEmoji: "🌾",
    daysLeft: 120,
    urgency: "green",
    quantity: "2 lbs extra",
    isAutoShared: false,
    requested: false,
  },
];

export const mockProfile: UserProfile = {
  name: "Sarah Chen",
  initials: "SC",
  savedThisMonth: 42,
  ingredientsRescued: 17,
  co2Saved: 3.2,
  mealsCooked: 9,
  notifications: [
    {
      id: "1",
      message:
        "Use your spinach today and save about $4, it expires tomorrow.",
      time: "2 hours ago",
      type: "warning",
      read: false,
    },
    {
      id: "2",
      message:
        "Strawberries have ~48 hours left, about $5 could hit the trash.",
      time: "5 hours ago",
      type: "warning",
      read: false,
    },
    {
      id: "3",
      message:
        "Whole milk’s date is Sunday, pour ~$2 into a soup or smoothie tonight.",
      time: "Yesterday",
      type: "warning",
      read: true,
    },
    {
      id: "4",
      message: "You prevented $18 of food waste this week. Keep it going.",
      time: "2 days ago",
      type: "success",
      read: true,
    },
  ],
};
